activate push event

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,7 +1,7 @@
 name: 01- building blocks
 
 on:
-    # push:
+    push:
     workflow_dispatch:
 
 jobs:
@@ -17,7 +17,9 @@ jobs:
 
         steps:
             - name: failed step
-              run: echo "I will fail"
+              run: |
+                echo "I will fail"
+                exit 1
 
             - name: say goodbye
               run: echo "Goodbye!"
